version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sa18Aa15Rh18Ca24
      - POSTGRES_DB=inmobiliaria